// This file is automatically generated by vscode-react-native@0.3.2
// Please do not modify it manually. All changes will be lost.
var React = require('g:\RN_softwares\app_projects\NianGao/node_modules/react');
var {Component} = React;

var ReactNative = require('g:\RN_softwares\app_projects\NianGao/node_modules/react-native');
var {AppRegistry} = ReactNative;

var entryPoint = require('g:\RN_softwares\app_projects\NianGao/index.ios.js');

AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('NianGao', appParameters);
});